---
- name: SSH Port Juggle | Try connecting via SSH
  ansible.builtin.wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_result

- name: SSH Port Juggle | Set the ansible_port to the fallback default port
  ansible.builtin.set_fact:
    ansible_ssh_port: "22"
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Try connecting again
  ansible.builtin.wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_result
  when:
    - _ssh_port_result is failed


- name: SSH Port Juggle | Set the ansible_port to the fallback default port and credentials
  ansible.builtin.set_fact:
    ansible_ssh_port: "22"
    ansible_ssh_user: "pi"
    ansible_ssh_password: "raspberry"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed

- name: Try default credentials (for Raspberry Pi)
  ansible.builtin.wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_cred_result
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed

- name: SSH Port Juggle | Try root
  ansible.builtin.set_fact:
    ansible_ssh_port: "22"
    ansible_ssh_user: "root"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed
    - _ssh_port_default_cred_result is failed

- name: Try root
  ansible.builtin.wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_root_result
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed
    - _ssh_port_default_cred_result is failed

- name: SSH Port Juggle | Fail
  ansible.builtin.fail:
    msg: "Neither the configured ansible_port {{ ansible_port }} nor the fallback port 22 were reachable"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is defined
    - _ssh_port_default_result is failed
    - _ssh_port_default_cred_result is defined
    - _ssh_port_default_cred_result is failed
    - _ssh_port_root_result is defined
    - _ssh_port_root_result is failed
